spring.application.name=up-me

frontend.url=http://localhost:3000

spring.datasource.url=jdbc:postgresql://localhost:5432/upme
spring.datasource.username=root
spring.datasource.password=123456789
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Config
spring.app.jwtSecret=keymySuperSecurekey1298371298739821739871298739812739879key
spring.app.jwtExpirationMs=172800000

# Business Logic
upme.user.monitor.max=5